apiVersion: v2
appVersion: 26.4.1
name: kube-downscaler
description: Downscaling tool to save on resources with dev clusters when they are not used
home: https://github.com/giantswarm/kube-downscaler-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
sources:
  - https://github.com/giantswarm/py-kube-downscaler
  - https://github.com/caas-team/py-kube-downscaler
dependencies:
  - name: py-kube-downscaler
    alias: kube-downscaler
    version: 0.3.12
    repository: https://caas-team.github.io/helm-charts/
    condition: enabled
version: 0.6.3
annotations:
  application.giantswarm.io/team: planeteers
