name: kube-downscaler
serviceType: managed

project:
  branch: "[[ .Branch ]]"
  commit: "[[ .SHA ]]"

image:
  registry: quay.io
  name: giantswarm/kube-downscaler
  tag: v0.0.1
  pullPolicy: IfNotPresent
