enabled: false

ciliumNetworkPolicy:
  enabled: false

daemonset:
  downscale: false
  job:
    image:
      registry: docker.io
      name: giantswarm/kubectl
      tag: 1.28.4
      pullPolicy: IfNotPresent
    # The downscaleSchedule Field must match the scalingInfo field's beginning time
    downscaleSchedule: "0 2 * * 6"
    # The upscaleSchedule Field must match the scalingInfo field's ending time
    upscaleSchedule: "0 22 * * 7"
  # A list of the daemonsets that should be downscaled. Each list's member must be as follows :
  # - name: <daemonset-name>
  #   namespace: <daemonset-namespace>
  list: []

kube-downscaler:
  image:
    repository: gsoci.azurecr.io/giantswarm/py-kube-downscaler
    pullPolicy: IfNotPresent
    tag: 25.3.0

  arguments:
  - --interval=60
  - --include-resources=deployments,statefulsets,scaledobjects,horizontalpodautoscalers

  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""

  excludedNamespaces: []

  configMapName: kube-downscaler

  extraConfig: |
    DOWNSCALE_PERIOD: "Sat-Sat 02:00-24:00 CET,Sun-Sun 00:00-22:00 CET"
    DOWNTIME_REPLICAS: 1

  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault

  podSecurityContext:
    fsGroup: 1000
    runAsGroup: 1000
    runAsNonRoot: true
    runAsUser: 1000
    seccompProfile:
      type: RuntimeDefault
