{{- if .Values.ciliumNetworkPolicy.enabled -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: {{ template "kube-downscaler.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "labels.common" . | nindent 4 }}
spec:
  egress:
  - toEntities:
    - kube-apiserver
    - world
  - toEndpoints:
    - matchLabels:
        k8s-app: coredns
    - matchLabels:
        k8s-app: k8s-dns-node-cache
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      - port: "1053"
        protocol: ANY
      rules:
        dns:
        - matchPattern: '*'
  - toEndpoints:
    - matchLabels:
        app.kubernetes.io/name: ingress-nginx
    toPorts:
    - ports:
      - port: "80"
        protocol: ANY
      - port: "443"
        protocol: ANY
  endpointSelector:
    matchLabels:
    {{- include "labels.selector" . | nindent 6 }}
{{- end }}
