{{- if .Values.ciliumNetworkPolicy.enabled -}}
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  labels:
  {{- include "labels.common" . | nindent 4 }}
  name: {{ template "kube-downscaler.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  egress:
  - toEntities:
    - kube-apiserver
  - toEndpoints:
    - matchLabels:
        k8s-app: coredns
    - matchLabels:
        k8s-app: k8s-dns-node-cache
    toPorts:
    - ports:
      - port: "53"
        protocol: ANY
      - port: "1053"
        protocol: ANY
      rules:
        dns:
        - matchPattern: '*'
  endpointSelector:
    matchLabels:
      application: {{ template "kube-downscaler.name" . }}
{{- end }}
