apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  {{- include "labels.common" . | nindent 4 }}
  name: {{ template "kube-downscaler.name" . }}
  namespace: {{ .Release.Namespace }}
data:
{{ .Values.scalingInfo | indent 2 }}
