apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }}
  name: {{ template "kube-downscaler.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "labels.common" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "labels.common" . | nindent 8 }}
    spec:
      serviceAccountName: {{ template "kube-downscaler.name" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ template "kube-downscaler.name" . }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        args:
        - --interval={{ .Values.interval }}
        {{- if .Values.debug.enable }}
        - --debug
        {{- end }}
        {{- with .Values.image.args }}
        {{ toYaml . | nindent 8 }}
        {{- end }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.resources }}
        resources:
          {{ toYaml . | nindent 10 }}
        {{- end }}
        envFrom:
          - configMapRef:
              name: "{{ template "kube-downscaler.name" . }}"
              optional: true
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
