{{- if .Values.rbac.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
  {{- include "labels.common" . | nindent 4 }}
  name: {{ template "kube-downscaler.name" . }}
{{- end -}}
