apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "labels.common" . | nindent 4 }} 
  name: {{ template "kube-downscaler.name" . }}-daemonset-downscaler
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kube-downscaler.name" . }}-daemonset-downscaler
subjects:
- kind: ServiceAccount
  name: {{ template "kube-downscaler.name" . }}-daemonset-downscaler
  namespace: {{ .Release.Namespace }}
